---
title: "Untitled"
author: "ST"
date: "2022/4/19"
output: html_document
---

```{r chapter2-1}
# comment
4+5
log(5)
exp(9)
sqrt(144)
```

```{r chapter2-2}
# object lesson
my_obj <- 9
My_obj <- 8
#大文字小文字は別

my_obj2 <- "R is cool."
print(my_obj2)

# add lesson
my_obj + My_obj #OK
#my_obj + my_obj2 #NG

my_obj3 <- "Hey!"
#my_obj2 + my_obj3 #NG

paste(my_obj3, my_obj2)
```

```{r chapter2-3}
# vector lesson
my_vec <- c(2,3,1,6,4,3,3,7)
print(my_vec)

mean(my_vec) #
var(my_vec) #
sd(my_vec) #
length(my_vec) #ベクトルのサイズ

my_vec2 <- c(2,3,1,6,4,3,3,7,NA)
var(my_vec2, na.rm = T)

my_seq <- 1:10
print(1:10)
my_seq <- seq(from=1, to=5, by=0.5)
print(my_seq)
```

```{r chapter2-4}
print(my_vec)
my_vec[2]
val_3 <- my_vec[3]

my_vec[c(1,5,6,8)]

id <- c(1,5,6,8)
print(my_vec[id])

my_vec[my_vec > 4]

id2 <- my_vec > 4
print(my_vec[id2])

id3 <- ((my_vec < 6) & (my_vec > 2))
my_vec[id3]

id4 <- ((my_vec > 6) | (my_vec <= 2))
my_vec[id4]
```

```{r chapter3-1}
num <- 2.2
char <- "hello"
logi <- TRUE

class(num)
class(char)
class(logi) #変数のデータ型がわかる$ class(変数名)

is.numeric(num)
is.character(char)
is.logical(logi) #変数のデータ型をT，Fで判定

num_char <- as.character(num)
print(num_char)
class(num_char)
```

```{r chapter3-2}
my_mat <- matrix(1:16, nrow=4, byrow=TRUE)
my_mat
my_mat2 <- matrix(1:16, nrow=4, byrow=FALSE)
my_mat2

my_array <- array(1:16, dim = c(2, 4, 2))
my_array

my_array[, , 1]
my_array[, 1, ]
my_array[1, , ]

rownames(my_mat) <- c("A","B","C","D")
colnames(my_mat) <- c("a","b","c","d")
my_mat

list_1 <- list(c("black","yellow","orange"),
               c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
               matrix(1:6, nrow=3))
list_1

list_2 <- list(c("black","yellow","orange"),
               c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
               time = matrix(1:6, nrow=3))
list_2

list_2$colors

str(list_2)

##data frames
p.height <- c(180, 155, 160, 167, 181)
p.weight <- c(65, 50, 52, 58, 70)
p.names <- c("Joanna", "Charlotte", "Helen", "Karen", "Amy")

dataf <- data.frame(height = p.height, weight = p.weight, names = p.names)
dataf
```

```{r chapter3-3}
flower[1,4]
flower[,c(1,4)] #1列と4列を取り出す
flower[c(1,4),] #1行と4列を取り出す
```

```{r tidyverse}
library(tidyverse)

flower %>% select(height)
flower %>% select(height, weight)
flower %>% select(-height, -weight)

flower_height <- flower %>% select(height)
flower_height

head(flower)

flower %>% filter(nitrogen == "high")

flower %>% 
  filter(nitrogen == "high") %>% 
  filter(height > 13) %>% 
  select(height, weight)

##問題　data.frameでどのように処理するか
flower$nitrogen=="high"
flower$weight>13
flower[flower$nitrogen=="high" & flower$height>13, c("height", "weight")]
#flowerを使って，flowerのnitogenをhigh,flower$height>13で
#c("height", "weight")このベクトルのとこ


#flower_2 <- flower %>% 
  
```

```{r chapter6-3}
#y ~ X1 + X2
#weight ~ height + leafarea

ans <- lm(weight ~ height + leafarea, data = flower)
summary(ans)

ans2 <- lm(weight ~ height * leafarea, data = flower)
summary(ans2)

```
```{r chapter7}

test_func <- function(x){
  y <- x+1
  return(y)
  }


test_func(7)

for(i in 1:5){
  test_func(i)
  print(i)
}
```


